USER_PROMPT_TITLE_ABSTRACT_YN = (
    "The title is: '{title}'. "
    "The abstract is: '{abstract}'. "
    "Answer 'Yes' or 'No' and nothing else."
)
USER_PROMPT_TITLE_CONTENT_YN = (
    "The title is: '{title}'. "
    "The abstract is: '{content}'. "
    "Answer 'Yes' or 'No' and nothing else."
)
USER_PROMPT_TITLE_CONTENT_OPEN = (  # TODO test
    "The title is: '{title}'. " "The content is: '{content}'. " "The answer is: "
)

TOKENIZATION_EXAMPLES = (
    "These are two examples with title and abstract:\n\n"
    "The title is: 'ADASPLASH: Adaptive Sparse Flash Attention'. \n"
    "The abstract is: 'The computational cost of softmax-based attention in transformers limits their applicability to long-context tasks. Adaptive sparsity, of which α-entmax attention is an example, offers a flexible data-dependent alternative, but existing implementations are inefficient and do not leverage the sparsity to obtain runtime and memory gains. In this work, we propose ADASPLASH, which combines the efficiency of GPU-optimized algorithms with the sparsity benefits of α-entmax. We first introduce a hybrid Halley-bisection algorithm, resulting in a 7-fold reduction in the number of iterations needed to compute the α-entmax transformation. Then, we implement custom Triton kernels to efficiently handle adaptive sparsity. Experiments with RoBERTa and ModernBERT for text classification and single-vector retrieval, along with GPT-2 for language modeling, show that our method achieves substantial improvements in runtime and memory efficiency compared to existing α-entmax implementations. It approachesand in some cases surpasses—the efficiency of highly optimized softmax implementations like FlashAttention-2, enabling long-context training while maintaining strong task performance.1' \n\n"
    "The answer is: No.\n\n"
    "The title is: 'Subword Regularization: Improving Neural Network Translation Models with Multiple Subword Candidates'. \n"
    "The abstract is: 'Subword units are an effective way to alleviate the open vocabulary problems in neural machine translation (NMT). While sentences are usually converted into unique subword sequences, subword segmentation is potentially ambiguous and multiple segmentations are possible even with the same vocabulary. The question addressed in this paper is whether it is possible to harness the segmentation ambiguity as a noise to improve the robustness of NMT. We present a simple regularization method, subword regularization, which trains the model with multiple subword segmentations probabilistically sampled during training. In addition, for better subword sampling, we propose a new subword segmentation algorithm based on a unigram language model. We experiment with multiple corpora and report consistent improvements especially on low resource and out-of-domain settings.' \n\n"
    "The answer is: Yes.\n\n"
    "Now, based on the title and content provided, determine whether the paper proposes a novel tokenization method or not.\n"
)

EVALUATION_EXAMPLES = (
    "These are two examples with title and abstract:\n\n"
    "The title is: 'Incorporating Context into Subword Vocabularies'.\n"
    "The abstract is: 'Most current popular subword tokenizers are trained based on word frequency statistics over a corpus, without considering information about co-occurrence or context. Nevertheless, the resulting vocabularies are used in language models' highly contextualized settings. We present SaGe, a tokenizer that tailors subwords for their downstream use by baking in the contextualized signal at the vocabulary creation phase. We show that SaGe does a better job than current widespread tokenizers in keeping token contexts cohesive, while not incurring a large price in terms of encoding efficiency or domain robustness. SaGe improves performance on English GLUE classification tasks as well as on NER, and on Inference and NER in Turkish, demonstrating its robustness to language properties such as morphological exponence and agglutination.' \n\n"
    "The answer is: No.\n\n"
    "The title is: 'Do All Languages Cost the Same? Tokenization in the Era of Commercial Language Models'. \n"
    "The abstract is: 'Language models have graduated from being research prototypes to commercialized products offered as web APIs, and recent works have highlighted the multilingual capabilities of these products. The API vendors charge their users based on usage, more specifically on the number of “tokens” processed or generated by the underlying language models. What constitutes a token, however, is training data and model dependent with a large variance in the number of tokens required to convey the same information in different languages. In this work, we analyze the effect of this nonuniformity on the fairness of an API’s pricing policy across languages. We conduct a systematic analysis of the cost and utility of OpenAI’s language model API on multilingual benchmarks in 22 typologically diverse languages. We show evidence that speakers of a large number of the supported languages are overcharged while obtaining poorer results. These speakers tend to also come from regions where the APIs are less affordable to begin with. Through these analyses, we aim to increase transparency around language model APIs’ pricing policies and encourage the vendors to make them more equitable.'. \n\n"
    "The answer is: Yes.\n\n"
    "Now, based on the title and content provided, determine whether the paper proposes a novel tokenization method or not.\n"
)

SURVEY_EXAMPLES = (
    "These are two examples with title and abstract:\n\n"
    "The title is: 'Between words and characters: A Brief History of Open-Vocabulary Modeling and Tokenization in NLP'.\n"
    "The abstract is: 'What are the units of text that we want to model? From bytes to multi-word expressions, text can be analyzed and generated at many granularities. Until recently, most natural language processing (NLP) models operated over words, treating those as discrete and atomic tokens, but starting with byte-pair encoding (BPE), subword-based approaches have become dominant in many areas, enabling small vocabularies while still allowing for fast inference. Is the end of the road character-level model or byte-level processing? In this survey, we connect several lines of work from the pre-neural and neural era, by showing how hybrid approaches of words and characters as well as subwordbased approaches based on learned segmentation have been proposed and evaluated. We conclude that there is and likely will never be a silver bullet singular solution for all applications and that thinking seriously about tokenization remains important for many applications.'.\n\n"
    "The answer is: Yes.\n\n"
    "The title is: 'Do All Languages Cost the Same? Tokenization in the Era of Commercial Language Models'. \n"
    "The abstract is: 'Language models have graduated from being research prototypes to commercialized products offered as web APIs, and recent works have highlighted the multilingual capabilities of these products. The API vendors charge their users based on usage, more specifically on the number of “tokens” processed or generated by the underlying language models. What constitutes a token, however, is training data and model dependent with a large variance in the number of tokens required to convey the same information in different languages. In this work, we analyze the effect of this nonuniformity on the fairness of an API’s pricing policy across languages. We conduct a systematic analysis of the cost and utility of OpenAI’s language model API on multilingual benchmarks in 22 typologically diverse languages. We show evidence that speakers of a large number of the supported languages are overcharged while obtaining poorer results. These speakers tend to also come from regions where the APIs are less affordable to begin with. Through these analyses, we aim to increase transparency around language model APIs’ pricing policies and encourage the vendors to make them more equitable.'. \n\n"
    "The answer is: No.\n\n"
    "Now, based on the title and content provided, determine whether the paper proposes a novel tokenization method or not.\n"
)

SYSTEM_PROMPT_FILTER = (  # ok for pixels, dynamic chunking, tok and noiseless channel, tokenization cost
    "You are a reviewer tasked with determining whether a research paper is related to tokenization based on its title and abstract. "
    "Given the title and abstract of the paper, decide if it is primarily focused on tokenization or not. "
    "This includes tokenization, tokenisation, subword segmentation, token free, vocabulary methods, alternatives to tokens."
)
SYSTEM_PROMPT_IS_TOKENISER = (
    "You are an helpful assistant tasked with determining whether a research paper proposes a novel tokenization method based on its title and abstract. "
    "Given the title and abstract of the paper, decide if its main goal is to introduce a new tokenizer."
)

SYSTEM_PROMPT_IS_EVALUATION = (  # ok for myte, noiseless channel, cost
    "You are an helpful assistant tasked with determining whether the main topic of a research paper is evaluating tokenizers rather than proposing new tokenization methods. "
    "Given the title and abstract of the paper, decide if its main goal is to discuss evaluation metrics for tokenizer and how to evaluate tokenizers."
)

SYSTEM_PROMPT_IS_SURVEY = (
    "You are an helpful assistant tasked with identifying research papers that provide a comprehensive survey of tokenization methods "
    "in natural language processing. Given the title and abstract of the paper, decide if it presents a "
    "systematic review or survey of tokenization methodologies, or provides a taxonomy, framework, or landscape of tokenization research."
)

SYSTEM_PROMPT_UNIT = (
    "You are an helpful assistant tasked with identifying the basic unit of analysis used by a tokenizer based on the title and content of a research paper. "
    "Given the title and content of the paper, determine what smaller units (such as words, characters, bytes, subwords, morphemes, pixels, or other) "
    "the tokenizer operates on. "
    "Do not distinguish between closely related categories."
    "Answer only with the list of most appropriate text units as '* {unit}\n' and nothing else."
)
USER_PROMPT_UNIT = (
    "The title is: '{title}'. \n"
    "The content is: '{content}'. \n\n"
    "What is the basic unit of analysis used by the tokenizer described in the paper? "
    "List the main text units that are used in the paper without any explanation and nothing else: "
)

SYSTEM_PROMPT_LANGUAGE = (
    "You are an helpful assistant tasked with identifying the languages that are used as test cases, evaluation datasets, or experimental targets "
    "in a research paper on tokenization given the title and content of the paper. "
)

USER_PROMPT_LANGUAGE_EN = (  # Output Yes/No
    "The title is: '{title}'. \n"
    "The content is '{content}'. \n\n"
    "Does the paper use exclusively English as the language for experiments, datasets, or evaluation? Answer 'Yes' or 'No' and nothing else. "
)

SYSTEM_PROMPT_LANGUAGE_MULTILINGUAL = (
    "You are an helpful assistant tasked with identifying the languages that are used as test cases, evaluation datasets, or experimental targets "
    "in a research paper on tokenization given the title and content of the paper. "
    "Answer only with the list of languages used and nothing else."
)

USER_PROMPT_LANGUAGE_MULTILINGUAL = (
    "The title is: '{title}'. \n"
    "The content is: '{content}'. \n\n"
    "List all the main languages that are used in the paper. Do not add any explanation."
)

SYSTEM_PROMPT_METRICS = (
    "You are an helpful assistant tasked with identifying the metrics that are used to evaluate tokenizers and downstream tasks "
    "in a research paper on tokenization given the title and content of the paper. "
    "Do not distinguish between closely related metrics. "
    "Answer only with the list of metrics used as '* {metric}\n' and nothing else."
)

USER_PROMPT_METRICS = (
    "The title is: '{title}'. \n"
    "The content is: '{content}'. \n\n"
    "List the main metrics used in the paper without any explanation and nothing else: "
)

SYSTEM_PROMPT_METRICS_TASKS = (
    "You are an helpful assistant tasked with identifying the tasks and metrics that are used to evaluate tokenizers "
    "in a research paper on tokenization given the title and content of the paper. "
    "Do not distinguish between closely related metrics or tasks. "
    "Answer only with the list of tasks and metrics used as '* {task}: {metric 1} {metrics 2} etc...\n' and nothing else."
)

USER_PROMPT_METRICS_TASKS = (
    "The title is: '{title}'. \n"
    "The content is: '{content}'. \n\n"
    "List the main tasks and metrics used in the paper without any explanation and nothing else: "
)

SYSTEM_PROMPT_MOTIVATION = (
    "You are an helpful assistant tasked with identifying the motivations behind a research paper on tokenization "
    "given the title and content of the paper."
)

USER_PROMPT_MOTIVATION = (
    "The title is: '{title}'. \n"
    "The content is: '{content}'. \n\n"
    # "Briefly summarize in a single sentence the main motivations behind the research presented in the paper and do not add anything else: "
    "Briefly summarize in a single sentence the main motivations behind the research presented in the paper and do not add anything else." 
    "The main motivation behind the research presented in the paper is "
)

SYSTEM_PROMPT_GENERIC = "You are an helpful assistant."
