[project]
name = "toksurvey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.15.0",
    "beautifulsoup4>=4.15.0",
    "bibtexparser>=2.0.0b2",
    "black>=26.5.1",
    "datasets>=5.0.1",
    "flashinfer-python>=0.6.18.post1",
    "ipdb>=0.13.13",
    "ipykernel>=7.3.0",
    "ipython>=9.17.1",
    "matplotlib>=3.11.2",
    "notebook>=7.6.3",
    "openreview-py>=2.6.2",
    "pandas>=3.0.6",
    "pyglottolog==3.16.0",
    "clldutils<4.0.0",
    "pymupdf4llm>=1.28.2",
    "python-iso639>=2026.7.23",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "sentence-transformers>=6.1.0",
    "torch>=2.13.0",
    "tqdm>=4.70.1",
    "transformers>=5.17.0",
    "vllm>=0.30.0",
    "xlsxwriter>=3.2.9",
]
